apiVersion: v1
kind: Pod
metadata:
  labels:
    run: quotes
  name: quotes
spec:
  containers:
  - name: quotes-docker
    image: docker-quotes:latest
    command: ['sh', '-c', 'java -classpath /home/quotes-3.3.0.0-RELEASE.jar:/home/commons-lang3-3.7.jar:/home/commons-logging-1.1.1.jar:/home/log4j-1.2.17.jar  com.eric.controller.CommandLineController -t' ]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
